# Dockerfile for RoleManagementService
FROM openjdk:11-jre-slim
COPY target/RoleManagementService-0.0.1-SNAPSHOT.jar RoleManagementService.jar
ENTRYPOINT ["java", "-jar", "/RoleManagementService.jar"]
