version: '3'
services:
  authentication-service:
    build: ./backend/authentication-service
  role-management-service:
    build: ./backend/role-management-service
  prescription-service:
    build: ./backend/prescription-service
  inventory-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ilr_inventory_db
  inventory-service:
    build: ./backend/inventory-service
    depends_on: 
      - inventory-db
  billing-service:
    build: ./backend/billing-service
  audit-log-service:
    build: ./backend/audit-log-service
  frontend:
    build: ./frontend/react-app
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - authentication-service
      - role-management-service
      - prescription-service
      - inventory-service
      - billing-service
      - audit-log-service
      - frontend
