# Dockerfile for AuthenticationService
FROM openjdk:11-jre-slim
COPY target/AuthenticationService-0.0.1-SNAPSHOT.jar AuthenticationService.jar
ENTRYPOINT ["java", "-jar", "/AuthenticationService.jar"]
